### ISSUE TITLE
Bad compiles render the mouse cursor a circle...forever.

### ISSUE THREAD

**Issue by cbmeeks** [parallaxinc/PropellerIDE#27]
On the Mac, if I build/compile a SPIN file and there is an error, it leaves my mouse cursor the spinning black-n-white circle.  I have to exit the IDE and reopen to fix.

This is on the newest version.

**Comment by bweir** [comment]
This is an issue on all platforms. I overlooked this when refactoring build
manager. When the new PropellerManager is integrated, I'll be fixing this
along with it.

**Comment by bweir** [comment]
This should no longer be an issue.
