### ISSUE TITLE
How to make and install

### ISSUE THREAD

**Issue by MPForsyth** [parallaxinc/PropellerIDE#34]
Nice looking Readme but some instructions on make and install would be helpful.
I extracted to my home directory.
By reading the sh files I thought I should run the script.sh first then the install.sh
I am installing on ubuntu 15.10
I received 'Invalid PLATFORM' from install.sh   so I export PLATFORM='linux'
  and try again
'packthing' command not found
now what ??

**Comment by bweir** [comment]
Hi there,

You can find build instructions here:

https://github.com/parallaxinc/PropellerIDE-docs/blob/master/docs/dev/building-propelleride.md

Sorry for the rubble. The PropellerIDE docs are all over the place while I
am writing a new manual, which is here:

https://bweir.gitbooks.io/propelleride/content/en/

So, if the first link disappears, it's because it's been moved to the
second.

Now a little more explanation.

The IDE uses qmake for its build system, then outsources packaging and
deployment to my experimental packthing tool. Make sure you use the git
version of packthing if you want to make a packaged build. If you just want
to play around with the code, you don't need anything other than Qt itself.

The scripts you found are actually part of the IDE's automated release
process, so you won't be needing them.

Hope that helps. Lemme know if you get stuck and I'll answer any questions
you have.

**Comment by MPForsyth** [comment]
Thanks Brett,
I tried following the instructions
git clone -ok
mikel@mikel-ThinkCentre-M78:~/PropellerIDE-master$ git submodule update --init --recursive
fatal: Not a git repository (or any of the parent directories): .git
qmake - OK
mikel@mikel-ThinkCentre-M78:~/PropellerIDE-master/PropellerIDE$ make -j16
cd src/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/mikel/PropellerIDE-master/PropellerIDE/src/src.pro -o Makefile ) && make -f Makefile 
make[1]: Entering directory '/home/mikel/PropellerIDE-master/PropellerIDE/src'
cd propellermanager/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/mikel/PropellerIDE-master/PropellerIDE/src/propellermanager/propellermanager.pro -o Makefile ) && make -f Makefile 
cd projectview/src/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/mikel/PropellerIDE-master/PropellerIDE/src/projectview/src/src.pro -o Makefile ) && make -f Makefile 
cd zipper/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/mikel/PropellerIDE-master/PropellerIDE/src/zipper/zipper.pro -o Makefile ) && make -f Makefile 
Cannot find file: /home/mikel/PropellerIDE-master/PropellerIDE/src/propellermanager/propellermanager.pro.
Makefile:72: recipe for target 'sub-propellermanager-make_first' failed
make[1]: *** [sub-propellermanager-make_first] Error 2
make[1]: *** Waiting for unfinished jobs....
Cannot find file: /home/mikel/PropellerIDE-master/PropellerIDE/src/projectview/src/src.pro.
Makefile:97: recipe for target 'sub-projectview-src-make_first' failed
make[1]: *** [sub-projectview-src-make_first] Error 2
make[2]: Entering directory '/home/mikel/PropellerIDE-master/PropellerIDE/src/zipper'
g++ -c -m64 -pipe -O2 -fPIC -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o zip.o zip.cpp
g++ -c -m64 -pipe -O2 -fPIC -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o zipper.o zipper.cpp
/usr/lib/x86_64-linux-gnu/qt5/bin/moc -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/mikel/PropellerIDE-master/PropellerIDE/src/zipper -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include zipper.h -o moc_zipper.cpp
g++ -c -m64 -pipe -O2 -fPIC -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o moc_zipper.o moc_zipper.cpp
rm -f libzipper.a
ar cqs libzipper.a zip.o zipper.o moc_zipper.o
make[2]: Leaving directory '/home/mikel/PropellerIDE-master/PropellerIDE/src/zipper'
make[1]: Leaving directory '/home/mikel/PropellerIDE-master/PropellerIDE/src'
Makefile:42: recipe for target 'sub-src-make_first' failed
make: *** [sub-src-make_first] Error 2
make - same results

**Comment by bweir** [comment]
Looks like you never checked out the submodules. You gotta go *into* the
repository and then run that command.

    $ cd PropellerIDE
    $ git submodule update --init --recursive

Then try the build again and you should be fine.

**Comment by MPForsyth** [comment]
So we need to add   cd PropellerIDE between  git lines in the instructions.

I removed the previous version and started the process over.
It encountered two errors in make
1
Project ERROR: Unknown module(s) in QT: serialport
Makefile:44: recipe for target 'sub-src-make_first' failed
make[2]: *** [sub-src-make_first] Error 3
make[2]: *** Waiting for unfinished jobs....
make[3]: Entering directory '/home/mikel/PropellerIDE-master/PropellerIDE/src/propellermanager/include'
make[3]: Nothing to be done for 'first'.
make[3]: Leaving directory '/home/mikel/PropellerIDE-master/PropellerIDE/src/propellermanager/include'
make[2]: Leaving directory '/home/mikel/PropellerIDE-master/PropellerIDE/src/propellermanager'
Makefile:72: recipe for target 'sub-propellermanager-make_first' failed
make[1]: *** [sub-propellermanager-make_first] Error 2
make[1]: *** Waiting for unfinished jobs....
2
Makefile:42: recipe for target 'sub-src-make_first' failed
make: *** [sub-src-make_first] Error 2

Serialport does not exist in  5.4 or 5.5   but qserialport does.

**Comment by bweir** [comment]
Hi there. What's the Qt version you're using? What is your operating system? What toolchain are you trying to build with?

**Comment by MPForsyth** [comment]
qt 5.4 is system wide and 5.5 is specific to my home.  Ubuntu Linux  15.10   and GCC

**Comment by bweir** [comment]
Ah, I see what's wrong now.

sudo apt-get install libqt5serialport5-dev

That should do the trick! I thought that was already in the documentation
but it wasn't, so I'll have to add it.

**Comment by MPForsyth** [comment]
Did the trick!
If you need some user side testing let me know.

**Comment by MPForsyth** [comment]
Very nice screens.  Love that memory map!

**Comment by bweir** [comment]
Well hey, I'm happy to hear it! The best thing you can do to help is to
make sure to play with each and every feature of the IDE to see how you
like it. You can help by telling everyone you know to switch to
PropellerIDE. :P

Also, if you or anyone you know is interested in developing PropellerIDE, I
can help get you set it. :)
