### ISSUE TITLE
Project manager and popups

### ISSUE THREAD

**Issue by MPForsyth** [parallaxinc/PropellerIDE#36]
Brett,
On version 0.0.0 and 0.33.3 the project manager shows the Pubs and Cons only for the first file and not for subsequent files.  Is this just not complete yet?

On version 0.0.0 typing the first OBJ name pops up the PUBS but on other OBJ gives only a  period.
On version0.33.3 the popup is only a period.  Is this just not complete yet.

I see you still have a incomplete manual - do you need help?  are you still using markdown?

**Comment by MPForsyth** [comment]
Just answered my own question. Found 0.36.5 and the reference to 0.36.7

**Comment by bweir** [comment]
Sorry about the late reply. I've been working on other projects for the last few days.

For the manual, I actually switched to AsciiDoc, as it offers a richer syntax, but the basic markup isn't fundamentally different from Markdown, and I would love some help documenting it.

A lot of pages are simply missing content. Have a look for yourself!
https://www.gitbook.com/book/bweir/propelleride/details

I'm currently busied by LameStation stuff so this manual hasn't seen much activity.

**Comment by MPForsyth** [comment]
I took a look at AsciiDoc - should be a breeze -.
Took a look at ..details -
Also have propelleride-docs- master  -  done in markup I guess.  Looks like
you took it down.
Where do I get the source so I can get started?

**Comment by bweir** [comment]
Hi there, I'm going to have to move the book out of GitBook for you to access because it has bizarre permissions. I will let you know when that's done.

Sorry I haven't responded lately. I have a big LameStation event coming up soon so I've been rather occupied.

**Comment by MPForsyth** [comment]
Hi Brett,
  I have the getting started chapter written.  I could just send them to
you for insertion if you wish.

Mike

**Comment by bweir** [comment]
Hi there. Sorry again. This weekend is actually the weekend of the event! But I managed to sneak this in.

You can now directly fork the PropellerIDE documentation, and from there, you can edit it as plaintext or use the GitBook editor. Then you can send a pull request for me to review.

https://github.com/parallaxinc/PropellerIDE-docs

Please let me know if there are any issues, otherwise I look forward to seeing what you have!
