### ISSUE TITLE
Several issues found in OSX version

### ISSUE THREAD

**Issue by PerryCodes** [parallaxinc/PropellerIDE#37]
Since this isn't the actual issue tracking system, and I don't have access to the Lamestation Jira... I'll post the URL to my description of these issues.

http://forums.parallax.com/discussion/163824/propelleride-user-experience

**Comment by bweir** [comment]
The saving issue and 'could not start' thing are fixed in [0.37.0](https://github.com/parallaxinc/PropellerIDE/releases/tag/0.37.0). You can track the progress of the usb port thing [here](https://lamestation.atlassian.net/browse/IDE-190), so I'm closing this one.

Please feel free to create an account and comment on the JIRA directly.

**Comment by PerryCodes** [comment]
Very nice!!  I am going to step up to your suggestion re: helping out with
the codebase.  I'm in the middle of developing a Caribbean rental-property
site, but once that's wrapped up, I'll start familiarizing myself with the
code and hopefully make myself useful ;)  Can't wait!

Regards ~ Jason P.
PerryCodes@gmail.com

**Comment by bweir** [comment]
Hi Perry,

I'm happy to hear it. Once you're free of your responsibilities, if you
need help getting up to speed on the code base, give me a ring and I'll
help you get set up. :)

Sincerely,

On Fri, Apr 8, 2016 at 8:05 AM, PerryCodes <notifications@github.com> wrote:

> Very nice!! I am going to step up to your suggestion re: helping out with
> the codebase. I'm in the middle of developing a Caribbean rental-property
> site, but once that's wrapped up, I'll start familiarizing myself with the
> code and hopefully make myself useful ;) Can't wait!
>
> Regards ~ Jason P.
> PerryCodes@gmail.com
>
> On Thu, Apr 7, 2016 at 7:13 AM, Brett Weir <notifications@github.com>
> wrote:
>
> > Closed #37 <https://github.com/parallaxinc/PropellerIDE/issues/37>.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/parallaxinc/PropellerIDE/issues/37#event-618295045>
> >
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/parallaxinc/PropellerIDE/issues/37#issuecomment-207470160>
>



-- 
*Brett Weir*, Founder


Engineering Made Awesome
310.245.1775  • brett@lamestation.com • lamestation.com
