### ISSUE TITLE
bstc compiler in PropellerIDE can't compile CON with negative #Expression 

### ISSUE THREAD

**Issue by dgately** [parallaxinc/PropellerIDE#45]
While compiling JonnyMac's string parsing example from the Parallax forum (see: [](http://forums.parallax.com/discussion/164930/unable-to-extract-data-from-a-string-and-save-to-variables#latest)) (downloaded project example file is: jm_parse_fields - Archive  [Date 2016), an error occurs with PropellerIDE's included bstc compiler...

The code:
`con
  #-1, ON, OFF                                                  ' digital control
  #0, LSBFIRST, MSBFIRST`

Image of PropellerIDE's error window:
<img width="769" alt="error1" src="https://cloud.githubusercontent.com/assets/3009364/17979117/f02b233e-6aad-11e6-9389-8a86bb27ff3b.png">

The constant "#-1,..." is failing as it appears bstc does not accept the '-' char.

The workaround is to place "()" around the negative value:
`con
  #(-1), ON, OFF                                                  ' digital control`

The above workaround is not needed for openspin or Parallax's original spin compiler...

**Comment by dgately** [comment]
Hmm... The "**" surrounding the CON expression was meant to bold the "-1" and "(-1)". Not sure why the issue editor did not work...

**Comment by dgately** [comment]
Code example attachment:
[jm_parse_fields - Archive  [Date 2016.08.23  Time 20.15].zip](https://github.com/parallaxinc/PropellerIDE/files/437685/jm_parse_fields.-.Archive.Date.2016.08.23.Time.20.15.zip)

**Comment by bweir** [comment]
Unfortunately, there isn't anything I can do about problems with bstc. =\
