### ISSUE TITLE
PropellerIDE FTBFS using newer compilers

### ISSUE THREAD

**Issue by avsa242** [parallaxinc/PropellerIDE#47]
PropellerIDE as of 29c3ddf24009cfe0ccbc52fcbbfce7b3613b00bd fails to build from source using compilers available in newer Linux distributions, such as gcc 6.2.1 in Ubuntu 16.10. gcc 5.4.0 in Gentoo ~amd64 also fails. The file it chokes on is:

`g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB -I. -I../propterm/include -I../propellermanager/include -I../projectview/include -I../memorymap/include -I../projectview/include -I../propellermanager/include -I../zipper -I../propellermanager/include -Icompilers -Iviews -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtSerialPort -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I.moc -I.ui -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o .obj/buildmanager.o buildmanager.cpp
In file included from buildmanager.h:14:0,
                 from buildmanager.cpp:1:
compilers/externalcompiler.h:33:14: error: ‘ExternalCompiler::ExternalCompiler(QString, QObject*)’ marked ‘override’, but does not override
     explicit ExternalCompiler(QString name,
              ^~~~~~~~~~~~~~~~
Makefile:833: recipe for target '.obj/buildmanager.o' failed
make[2]: *** [.obj/buildmanager.o] Error 1`

clang 3.8.1, also available in Ubuntu 16.10, successfully builds PropellerIDE.

Using the following to build:
`# export QT_SELECT=qt5`

in the top-level PropellerIDE sources directory,
`# qmake propelleride.pro`
`# make -j8`

**Comment by bweir** [comment]
Hi there,

Sorry I've been away for a long time. I started a new job in the last few weeks and so pretty much *everything* has fallen off my radar. I suppose I should make an announcement on the forum, but I haven't been there recently either.

It gives me great pain to see issues accumulating on PropellerIDE that aren't being fixed, but I don't know anyone who is willing to pick up the baton (which is how I ended up developing it in the first place!) I'm going to spend some time this weekend and see about fixing some of these issues.

If you're interested, perhaps you can email me at brett@lamestation.com with your Skype so we can chat in real-time about some of the problems you've been having, as I know this isn't the only one. I'd be happy to tell you about the project's current status from my perspective as well.

**Comment by bweir** [comment]
Hey, I found the problem. I was declaring an override on a constructor that wasn't overriding anything. =|

I checked it in already. Try it out, see if it works for you; if it does, I'll close this! I also noticed that my documentation for setting up the build environment is quite scant, so I'm trying to fix that now. >.>

**Comment by avsa242** [comment]
Brett,

Yeah I remember Googling to see exactly what the error meant but not really
understanding what was necessary to fix it. It didn't occur to me to simply
remove the override declaration (Even if it seemed to work, I wouldn't have
been confident it was the right way to fix it anyway, not knowing C++ or
QT5).
In any case,

gcc-5.4.0 (Gentoo ~amd64): Success
gcc-6.2.0-5ubuntu12 (Ubuntu amd64): Success
gcc-6.3.1 20170109 (Arch ARM64): Success

Thanks!

Jesse
