### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by 4c0n** [parallaxinc/PropellerIDE#58]
Hi!

It can be quite the hassle getting the IDE running on Linux. There have been numerous forum posts about it.
There are a lot of different distros out there, that people like to use and supporting package building for all of them can be a full time job on its own.

Flatpak aims to solve these issues by packing the application with pretty much all of its dependencies, so that it can be ran on any distro.

See for more info:
https://flatpak.org/
https://flathub.org/home

I've put in some effort to make a manifest and forked the repositories where modifications where required.
There are still some things to be done, but since a lot of it is working already, I thought I'd start looking into how to publish the application on Flathub (a central repository where applications can be installed from).

Turns out they prefer to have the official author of the software to publish it. Which I can totally understand.

In order to move forward with this we'd have to decide on the following:
- Are you interested in publishing the PropellerIDE and its bundled software on Flathub?
- If so, shall I open PRs for the modifications to the repositories? (Just adding install targets to the qmake configuration here and there)
- Are you available to help publish the manifest or would you like for me to do that (requires some level of access to the github organization parallaxinc)?

You can find the manifest here: https://github.com/4c0n/propeller-ide-flatpak

Thanks in advance for your time and effort!

**Comment by bweir** [comment]
Hi Youri,

Let's connect! You can find my email address in the commit log for this
repository, haha.

I think it'd be great to have a flatpak distribution of PropellerIDE. Let's
discuss how we can make that happen.

Sincerely,
